name: Deploy Jupyter Book to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -U jupyter-book ghp-import

      - name: Build the book
        run: jupyter-book build mybook/

      - name: Deploy to GitHub Pages
        run: ghp-import -n -p -f mybook/_build/html
